# Generated by Django 4.1.3 on 2022-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartfashion',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='rating3',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='rating4',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='rating5',
        ),
    ]
