# Generated by Django 4.1.3 on 2022-11-03 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_smartfashion_rating2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingcollection',
            old_name='feedback',
            new_name='dressprice',
        ),
        migrations.RenameField(
            model_name='weddingcollection',
            old_name='payment_card',
            new_name='dressqnty',
        ),
        migrations.RenameField(
            model_name='weddingcollection',
            old_name='total',
            new_name='rating1',
        ),
        migrations.RemoveField(
            model_name='weddingcollection',
            name='payment',
        ),
        migrations.AddField(
            model_name='weddingcollection',
            name='total_amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
