# Generated by Django 4.1.3 on 2022-11-03 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_dressprice_smartfashion_customerage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='customeraddress',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='customerphnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
