# Generated by Django 4.1.3 on 2022-11-05 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartfashion',
            name='dressrating',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
