# Generated by Django 4.1.3 on 2022-11-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_smartfashion_dressrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartfashion',
            name='dressrating',
        ),
    ]
