# Generated by Django 4.1.1 on 2022-11-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_genscollectionpayment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='girlscollectionpayment',
            name='date',
        ),
    ]
