# Generated by Django 4.1.3 on 2022-11-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paymentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartfashion',
            old_name='dressprice',
            new_name='customerage',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='dressqnty',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='rating1',
        ),
        migrations.RemoveField(
            model_name='smartfashion',
            name='total_amount',
        ),
    ]
