# Generated by Django 4.1.3 on 2022-11-03 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paymentdetails_customeraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='dressprice',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
