# Generated by Django 4.0.4 on 2022-11-07 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_smartfashion_dressrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='customeremail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='dresscolor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
