# Generated by Django 4.0.4 on 2022-11-07 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_girlscollectionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlscollectionpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='girlscollectionpayment',
            name='size',
            field=models.CharField(choices=[('7meters', '7meters'), ('8meters', '8meters')], default='1', max_length=20),
        ),
    ]
