# Generated by Django 4.0.4 on 2022-11-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_girlscollectionpayment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girlscollectionpayment',
            old_name='size',
            new_name='dresssize',
        ),
    ]
