# Generated by Django 4.0.4 on 2022-11-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_size_girlscollectionpayment_dresssize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genscollectionpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=100)),
                ('customeremail', models.EmailField(max_length=254)),
                ('customerphnumber', models.CharField(max_length=100)),
                ('customeraddress', models.CharField(max_length=100)),
                ('dressname', models.CharField(max_length=100)),
                ('dresscolor', models.CharField(max_length=100)),
                ('dressprice', models.CharField(max_length=100)),
                ('dresssize', models.CharField(choices=[('7meters', '7meters'), ('8meters', '8meters')], default='1', max_length=20)),
                ('dressqnty', models.CharField(max_length=100)),
                ('dressamount', models.CharField(max_length=100)),
                ('paymentstype', models.CharField(choices=[('Paytm', 'Paytm'), ('GooglePay', 'GooglePay'), ('Freecharge', 'Freecharge'), ('YonoSBI', 'YonoSBI'), ('Payzapp', 'Payzapp')], default='1', max_length=20)),
                ('accountnumber', models.CharField(max_length=100)),
                ('deliverydate', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
