# Generated by Django 4.0.4 on 2022-11-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_genscollectionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genscollectionpayment',
            name='dresssize',
        ),
        migrations.AddField(
            model_name='genscollectionpayment',
            name='size',
            field=models.CharField(choices=[('1', 'M'), ('2', 'S'), ('3', 'L'), ('4', 'XL'), ('4', 'XXL')], default='1', max_length=20),
        ),
    ]
