# Generated by Django 4.1.1 on 2022-11-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_paymentdetails_delete_smartfashion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genscollectionpayment',
            name='date',
        ),
    ]
