# Generated by Django 4.1.1 on 2022-11-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_addprodadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='jean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressimages', models.ImageField(upload_to='')),
                ('dress_name', models.CharField(max_length=20)),
                ('dress_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='lycrapant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressimages', models.ImageField(upload_to='')),
                ('dress_name', models.CharField(max_length=20)),
                ('dress_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressimages', models.ImageField(upload_to='')),
                ('dress_name', models.CharField(max_length=20)),
                ('dress_amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dressimages', models.ImageField(upload_to='')),
                ('dress_name', models.CharField(max_length=20)),
                ('dress_amount', models.CharField(max_length=10)),
            ],
        ),
    ]
