# Generated by Django 4.1.1 on 2022-11-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_jean_lycrapant_shirt_vesti'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jean',
            new_name='vestiandshirrtspattu',
        ),
    ]
